name: DevSecOps CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Python Version
        run: python3 --version

      - name: Create Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip

      - name: Install Dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          source venv/bin/activate
          pytest -v

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Snyk Python Dependency Scan
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --file=requirements.txt

      - name: Build Docker Image
        run: |
          docker build --pull \
            -t devsecops-flask-app:${{ github.sha }} .

      - name: Snyk Docker Image Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk container test \
            devsecops-flask-app:${{ github.sha }} \
            --file=Dockerfile \
            --severity-threshold=high