name: DevSecOps CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Python Version
        run: python3 --version

      - name: Create Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip

      - name: Install Dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          source venv/bin/activate
          pytest -v

      # SonarQube Cloud
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Snyk dependency security scan
      - name: Snyk Dependency Scan
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --file=requirements.txt

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build --pull -t devsecops-flask-app:${{ github.sha }} .

      # Install Snyk CLI
      - name: Install Snyk CLI
        run: |
          curl --compressed https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x snyk
          sudo mv snyk /usr/local/bin/snyk
          snyk --version

      # Scan Docker image with Snyk
      - name: Scan Docker Image with Snyk
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk container test devsecops-flask-app:${{ github.sha }} \
            --severity-threshold=high